### ISSUE TITLE
No javadoc/source of this repository is imported in AndroidStudio/Gradle project

### ISSUE THREAD

**Issue by coryffaeus** [memoizr/retro-optional#4]
Hey, I used retro-optional as a dependency in Gradle to use in an AndroidStudio project and while the binaries imported properly, I can't see either javadoc or sources. Jitpack documentation states that it is up to the repository owner to configure the published artefacts to either include or not include the sources/docs. Could you please, check that? Thanks!

**Comment by memoizr** [comment]
Sure, I'll have a look!

**Comment by memoizr** [comment]
I checked, and the source and documentation jars should be distributed already as of version 0.2.0. 
Here's Jitpack's log:
![image](https://user-images.githubusercontent.com/10452220/27480356-966de2fa-580f-11e7-8d18-0def5200762d.png)

Also, I tested it on a project, and I was able to see both source and documentation. Could you please make sure your IDE is set up correctly to download sources and docs for libraries?

**Comment by coryffaeus** [comment]
Thanks a lot for getting back and checking! I had sources/javadocs from other libraries, that's why I asked. But let me double-check again, maybe the IDE/Gradle was in some weird state.
